#!/bin/bash
# Version 0.4

DIR="Red-DiscordBot"
BOT="red.py"
LOG="/home/ubuntu/botcrashtimes.log"
HELP="Args: git, bot, kill, yt (updates yt-dl)"

if [ -z "$*" ]; then
	echo $HELP
else
    if [ "$1" = "git" ]; then
        cd $DIR
        git pull
        cd ..
		echo "Run ./run to update 'sys's"
    elif [ "$1" = "bot" ]; then
        cd $DIR
        python3 $BOT &
		cd ..
	elif [ "$1" = "abot" ]; then
        cd $DIR
        python3 $BOT &
		while true;	do
			if ps -p $! > /dev/null; then
				echo "Bot is still running"
			else
				echo "$(date) $line" > $LOG
				python3 $BOT &
			fi
		done
		cd ..
    elif [ "$1" = "kill" ]; then
        pkill -f red.py
	elif [ "$1" = "yt" ]; then
		sudo -H pip install --upgrade youtube-dl
    else
        echo $HELP
    fi
fi
